class Constant {
    static FIREBASE_REALTIME_DATABASE_PRIVATE_USER_DATA_REF_NAME = "private_user_data"
    static ONLINE = "online"
    static USER_ONLINE_STATUS_SOCKET_EVENT = "USER_ONLINE_STATUS_SOCKET_EVENT"
    static USER_VERIFIED_STATUS_SOCKET_EVENT = "USER_VERIFIED_STATUS_SOCKET_EVENT"
    static VERIFIED = "verified"
    static NEW_MESSAGE_SOCKET_EVENT = "NEW_MESSAGE_SOCET_EVENT"
}

export default Constant